package com.cognizant.BookingService.entity;

import jakarta.persistence.*;
import lombok.Data;
import com.fasterxml.jackson.annotation.JsonProperty;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "booking_service")
@EntityListeners(AuditingEntityListener.class)
public class BookingServiceEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "booking_id")
    @JsonProperty("bookingId")
    private Long bookingId;

    @Column(name = "user_id")
    @JsonProperty("userId")
    private Long userId; // Reference to user_service entity

    @Column(name = "game_id")
    @JsonProperty("gameId")
    private Long gameId; // Reference to game_catalog entity

    @Column(name = "allotment_id")
    @JsonProperty("allotmentId")
    private Long allotmentId;

    @Column(name = "booking_location")
    @JsonProperty("bookingLocation")
    private String bookingLocation;

    @Column(name = "booking_start_time")
    @JsonProperty("bookingStartTime")
    private LocalDateTime bookingStartTime;

    @Column(name = "booking_end_time")
    @JsonProperty("bookingEndTime")
    private LocalDateTime bookingEndTime;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "modified_at")
    private LocalDateTime modifiedAt;

    // Getters and setters can be generated by Lombok or manually if needed
}
